# Numpy

In [1]:
import numpy as np
import matplotlib.pyplot as plt 
import os

### <span style='background :yellow'>Funzioni base
#### Funzione ARRAY - Creazione di un array

In [2]:
a = np.array([1,2,3,4,5]) # l'argomento passato è una lista
a

array([1, 2, 3, 4, 5])

#### Funzione ARRAY - Creazione di una matrice

In [3]:
b = np.array([[1,2,3,4,5],[6,7,8,9,10]]) # l'argomento passato è una lista
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

#### Ottenere singola cella di un array e matrice

In [4]:
a[0] # prima posizione dell'array

1

In [5]:
b[0,0] # prima riga e prima colonna della matrice

1

#### Funzione NDIM - Ottenere dimensione di un array e matrice

In [6]:
a.ndim # dimensione array

1

In [7]:
b.ndim # dimensione matrice

2

#### Funzione SHAPE - Grandezza di un array e matrice

In [8]:
a.shape # grandezza array

(5,)

In [9]:
b.shape # grandezza matrice

(2, 5)

#### Funzione SIZE - Numero elementi di un array e matrice

In [10]:
a.size # elementi array

5

In [11]:
b.size # elementi matrice

10

### <span style='background :yellow'>Creazione matrici con funzioni
#### Funzione ONES - Creazione di matrici contenenti 1

In [12]:
a = np.ones((3,2), dtype=int)
a

array([[1, 1],
       [1, 1],
       [1, 1]])

#### Funzione ZEROS - Creazione di matrici contenenti 0

In [13]:
a = np.zeros((3,2), dtype=int)
a

array([[0, 0],
       [0, 0],
       [0, 0]])

#### Funzione RANDOM - Creazione di matrici casuali

In [14]:
a = np.random.random((3,2))
a

array([[0.51476388, 0.00541482],
       [0.36791644, 0.50510945],
       [0.46295076, 0.55263193]])

#### Funzione FULL - Creazione di matrici contenenti un numero scelto

In [15]:
a = np.full((3,2), 10)
a

array([[10, 10],
       [10, 10],
       [10, 10]])

### <span style='background :yellow'>Creazione sequenze
#### Funzione ARANGE

In [16]:
a = np.arange(0,10,2) # start, stop, step
a

array([0, 2, 4, 6, 8])

#### Funzione LINSPACE

In [17]:
a = np.linspace(0,10,5) # start, stop, numeri tra intervallo
a

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

### <span style='background :yellow'>Modificare array
#### Funzione RESIZE

In [18]:
a = np.arange(0,10,1) # start, stop, step
print(a.shape)
a

(10,)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
a.resize(2,5)
print(a.shape)
a

(2, 5)


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [20]:
a.resize(5,2)
print(a.shape)
a

(5, 2)


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

#### Funzione RAVEL

In [21]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [22]:
c = a.ravel()
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Funzione TRANSPOSE

In [23]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [24]:
c = a.transpose()
c

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

### <span style='background :yellow'>Array slicing
#### Array

In [25]:
a = np.arange(0, 30, 2)
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [26]:
b = a[1:6] # intervallo tra elementi in posizione 1 e (6-1)
b

array([ 2,  4,  6,  8, 10])

In [27]:
b = a[:5] # primi 5 elementi
b

array([0, 2, 4, 6, 8])

In [28]:
b = a[5:] # da elemento 5 in poi
b

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [29]:
b[0] = 100 # modifica del primo elemento dell'array
b

array([100,  12,  14,  16,  18,  20,  22,  24,  26,  28])

#### Matrici

In [30]:
a = np.array([[0,1,2,3,4],[5,6,7,8,9]])
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [31]:
b = a[0:1,1] # 0:1 prende solamente la posizione 0, perchè sarebbe da 0 ad (1-1) = 0, ma permette di mantere la struttura array (altrimenti restituirebbe un numero)
b

array([1])

In [32]:
b = a[:,1] # tutte le righe, soltanto la colonna 1
b

array([1, 6])

In [33]:
b = a[...,1] # tutte le righe, soltanto la colonna 1 (altro metodo)
b

array([1, 6])

### <span style='background :yellow'>Funzioni aritmetiche

In [34]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [35]:
b = np.array([[11,12,13,14,15],[16,17,18,19,20]])
b

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

#### Funzione ADD - somma tra due array/matrici

In [36]:
c = np.add(a,b) # somma delle due matrici sopra
c

array([[12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [37]:
c = a + b # metodo alternativo
c

array([[12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

#### Funzione SUBTRACT - sottrazione tra due array/matrici

In [38]:
c = np.subtract(b,a) # somma delle due matrici sopra
c

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [39]:
c = b - a # metodo alternativo
c

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

#### Funzione REMAINDER - modulo divisione tra due array/matrici

In [40]:
c = np.remainder(b,a) # modulo divisione delle due matrici sopra
c

array([[0, 0, 1, 2, 0],
       [4, 3, 2, 1, 0]])

#### Funzione POWER - elevare a potenza un array/matrice

In [41]:
c = np.power(a,2) # potenza base 2 della matrice a
c

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100]], dtype=int32)

#### Maschere

In [42]:
mask = a < 5 # filtro per valori della matrice a < 5
print(mask)
c = a[mask]
c

[[ True  True  True  True False]
 [False False False False False]]


array([1, 2, 3, 4])

### <span style='background :yellow'>Funzioni elementari

In [43]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [44]:
b = np.array([[-1.5,2.3],[-3.1,4.9]])
b

array([[-1.5,  2.3],
       [-3.1,  4.9]])

#### Funzione EXP - esponenziale di un array/matrice

In [45]:
c = np.exp(a) # esponenziale della matrice a
c

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

#### Funzione SQRT - radice quadrata di un array/matrice

In [46]:
c = np.sqrt(a) # radice quadrata della matrice a
c

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

#### Funzione LOG - logaritmo naturale di un array/matrice

In [47]:
c = np.log(a) # logaritmo naturale della matrice a
c

array([[0.        , 0.69314718],
       [1.09861229, 1.38629436]])

#### Funzione AROUND - arrotondamento per eccesso o difetto di un array/matrice

In [48]:
c = np.around(b) # arrotondamento della matrice b
c

array([[-2.,  2.],
       [-3.,  5.]])

#### Funzione FLOOR - arrotondamento per difetto di un array/matrice

In [49]:
c = np.floor(b) # arrotondamento per difetto della matrice b
c

array([[-2.,  2.],
       [-4.,  4.]])

#### Funzione CEIL - arrotondamento per eccesso di un array/matrice

In [50]:
c = np.ceil(b) # arrotondamento per difetto della matrice b
c

array([[-1.,  3.],
       [-3.,  5.]])

#### Funzione TRUNC - eliminazione della parte decimale di un array/matrice

In [51]:
c = np.trunc(b) # arrotondamento per difetto della matrice b
c

array([[-1.,  2.],
       [-3.,  4.]])

### <span style='background :yellow'>Funzioni array

In [52]:
a = np.array([[1,7,3,9,5],[6,2,8,4,10]])
a

array([[ 1,  7,  3,  9,  5],
       [ 6,  2,  8,  4, 10]])

In [53]:
b = np.array([[11,12,13,14,15],[16,17,18,19,20]])
b

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

#### Funzione SUM - somma su assi di un array/matrice

In [54]:
c = a.sum(axis=0) # somma delle colonne
c

array([ 7,  9, 11, 13, 15])

In [55]:
c = a.sum(axis=1) # somma delle righe
c

array([25, 30])

#### Funzione MIN - valore più piccolo di un array/matrice

In [56]:
c = np.min(a)
c

1

#### Funzione MAX - valore più grande di un array/matrice

In [57]:
c = np.max(a)
c

10

In [58]:
c = a.max(axis=0) # valore massimo su ogni colonna
c

array([ 6,  7,  8,  9, 10])

In [59]:
c = a.max(axis=1) # valore massimo su ogni riga
c

array([ 9, 10])

#### Funzione CUMSUM - somma di tutti i valori di un array/matrice

In [60]:
a

array([[ 1,  7,  3,  9,  5],
       [ 6,  2,  8,  4, 10]])

In [61]:
c = np.cumsum(a, axis=0) # somma cumulativa su ogni colonna
c

array([[ 1,  7,  3,  9,  5],
       [ 7,  9, 11, 13, 15]])

In [62]:
c = np.cumsum(a, axis=1) # somma cumulativa su ogni colonna
c

array([[ 1,  8, 11, 20, 25],
       [ 6,  8, 16, 20, 30]])

#### Funzione CORCOEFF - coefficente di correlazione di un array/matrice

In [63]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [64]:
c = np.corrcoef(a)
c

1.0

#### Funzione STD - deviazione standard
Probabilità che un valore si discosti dal valore medio

In [65]:
a = np.array([1,2,3,4,5])

In [66]:
a.mean() # la media è pari a 3

3.0

In [67]:
c = a.std()
c

1.4142135623730951

La deviazione standard è pari a 1.4. Ciò significa che un prossimo campione, con molta probabilità, si discosterà dalla media di +- 1.4
Più i campioni si avvicinano alla media, e più la deviazione standard diminuisce
Se tutti i campioni avessero lo stesso valore, la deviazione standard sarebbe pari a 0

In [68]:
a = np.array([3,3,3,3,3])

a.mean() # la media è pari a 3

c = a.std()
c

0.0