# Numpy

In [1]:
import numpy as np

### <span style='background :yellow'>Creazione array

#### Funzione ARRAY - creazione di array (NxM) tramite liste

In [2]:
# creazione di un array monodimensionale
a = np.array([1,2,3,4,5], dtype='int8') # l'argomento passato è una lista, viene inoltre specificato il tipo che si vuole per i dati (int8)
a

array([1, 2, 3, 4, 5], dtype=int8)

In [3]:
# creazione di un array bidimensionale (matrice)
b = np.array([[1,2,3,4,5],[6,7,8,9,10]])
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

#### Funzione ONES - Creazione di array (NxM) di 1

In [4]:
a = np.ones(5, dtype=int)
a

array([1, 1, 1, 1, 1])

In [5]:
a = np.ones((3,2), dtype=int)
a

array([[1, 1],
       [1, 1],
       [1, 1]])

#### Funzione ZEROS - Creazione di array (NxM) di 0

In [6]:
a = np.zeros(5, dtype=int)
a

array([0, 0, 0, 0, 0])

In [7]:
a = np.zeros((3,2), dtype=int)
a

array([[0, 0],
       [0, 0],
       [0, 0]])

#### Funzione RANDOM - Creazione di array (NxM) casuali

In [8]:
# creazione di un array con numeri casuali compresi fra 0 ed 1
a = np.random.random(5)
a

array([0.63424545, 0.76587723, 0.55136231, 0.24868765, 0.79314108])

In [9]:
# creazione di un array 3x2 con numeri casuali compresi fra 0 ed 1
a = np.random.random((3,2))
a

array([[0.79502764, 0.37270198],
       [0.3954705 , 0.20647409],
       [0.2739486 , 0.55176762]])

In [10]:
# stesso risultato della soluzione sopra
a = np.random.rand(3,2)
a

array([[0.56012655, 0.03639964],
       [0.27429916, 0.07346084],
       [0.02104254, 0.36397359]])

In [11]:
# creazione di un array 3x2 con numeri casuali compresi fra 3 e (10-1)
a = np.random.randint(3,10,size=(3,2))
a

array([[3, 8],
       [5, 4],
       [6, 9]])

#### Funzione FULL - Creazione di array (NxM) con numero scelto

In [12]:
a = np.full(5, 10)
a

array([10, 10, 10, 10, 10])

In [13]:
a = np.full((3,2), 10)
a

array([[10, 10],
       [10, 10],
       [10, 10]])

In [14]:
b = np.full(a.shape, 10)
b

array([[10, 10],
       [10, 10],
       [10, 10]])

#### Funzione IDENTITY/EYE -  Creazione di una matrice identità (NxN)

In [15]:
a = np.identity(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Funzione REPEAT

In [17]:
a = np.array([[1,2,3]])
a

array([[1, 2, 3]])

In [18]:
b = np.repeat(a, 3, axis=0)
b

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [19]:
b = np.repeat(a, 3, axis=1)
b

array([[1, 1, 1, 2, 2, 2, 3, 3, 3]])

#### Funzione ARANGE

In [20]:
a = np.arange(0,10,2) # start, stop, step
a

array([0, 2, 4, 6, 8])

#### Funzione LINSPACE

In [21]:
a = np.linspace(0,10,5) # start, stop, numeri tra intervallo
a

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

### <span style='background :yellow'>Funzioni base

In [22]:
a = np.array([1,2,3,4,5,6,7,8,9,10], dtype='int8') # l'argomento passato è una lista, viene inoltre specificato il tipo che si vuole per i dati (int8)
b = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [23]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [24]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

#### Funzione DTYPE - Ottenere tipo di un array e matrice

In [25]:
a.dtype

dtype('int8')

In [26]:
b.dtype

dtype('int32')

#### Funzione ASTYPE - Cambiare tipo di un array e matrice

In [27]:
a # il type è int8

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [28]:
a.astype('int16') # questa funzione trasformata in int16

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int16)

In [29]:
a # stampando però a, risulta ancora int8 in quanto non è stata fatta nessuna associazione con la funzione sopra

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [30]:
a = a.astype('int16')

In [31]:
a # a finalmente risulta int16

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int16)

#### Funzione SIZE - Numero elementi di un array e matrice

In [32]:
a.size # elementi array

10

In [33]:
b.size # elementi matrice

10

#### Funzione ITEMSIZE - Ottenere size in byte di un singolo elemento di un array e matrice

In [34]:
a.itemsize

2

In [35]:
b.itemsize

4

#### Funzione NBYTES - Ottenere size totale in byte di un array e matrice

In [36]:
a.nbytes # a.size * a.itemsize

20

In [37]:
b.nbytes # b.size * b.itemsize

40

#### Funzione NDIM - Ottenere dimensione di un array e matrice

In [38]:
a.ndim # dimensione array

1

In [39]:
b.ndim # dimensione matrice

2

#### Funzione SHAPE - Grandezza di un array e matrice

In [40]:
a.shape # grandezza array

(10,)

In [41]:
b.shape # grandezza matrice

(2, 5)

### <span style='background :yellow'>Modificare array

In [42]:
a = np.array([1,2,3,4,5,6,7,8,9,10], dtype='int8') # l'argomento passato è una lista, viene inoltre specificato il tipo che si vuole per i dati (int8)

In [43]:
print(a.shape)
a

(10,)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

#### Funzione RESIZE - Cambiare numero di righe e colonne della matrice
La funzione resize non ritorna nulla, e modifica la matrice originale

In [44]:
a.resize(2,5) # da uno shape (1,10) si passa ad uno shape (2,5)
print(a.shape)
a

(2, 5)


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]], dtype=int8)

In [45]:
a.resize(5,2) # da uno shape (2,5) si passa ad uno shape (5,2)
print(a.shape)
a

(5, 2)


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]], dtype=int8)

#### Funzione RESHAPE - Cambiare numero di righe e colonne della matrice
La funzione reshape ritorna una nuova matrice, e non modifica la matrice originale

In [46]:
print(a.shape) # la matrice originale ha uno shape (5,2)
a

(5, 2)


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]], dtype=int8)

In [47]:
a.reshape(2,5) # da uno shape (5,2) si vuole passare ad uno shape (2,5), ma come si può notare dall'output lo shape di a rimane (5,2)
print(a.shape)
a

(5, 2)


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]], dtype=int8)

In [48]:
b = a.reshape(2,5) # facendo l'assegnazione, la nuova matrice ha lo shape voluto (2,5)
print(b.shape)
b

(2, 5)


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]], dtype=int8)

#### Funzione RAVEL - Rendere il vettore monodimensionale

In [49]:
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]], dtype=int8)

In [50]:
c = a.ravel()
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

#### Funzione TRANSPOSE - Ottenere la matrice trasposta

In [51]:
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]], dtype=int8)

In [52]:
c = a.transpose()
c

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]], dtype=int8)

#### Funzione VSTACK - Unire verticalmente più vettori

In [53]:
a = np.array([[1,2,3],[4,5,6]]) # i due vettori devono avere lo stesso numero di colonne
b = np.array([1,2,3])

In [54]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
b

array([1, 2, 3])

In [56]:
np.vstack([a,b])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [57]:
np.vstack([a,b,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

#### Funzione HSTACK - Unire orizzontalmente più vettori

In [58]:
a = np.array([[1,2,3],[4,5,6]]) # i due vettori devono avere lo stesso numero di righe
b = np.array([[1,2],[3,4]])

In [59]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
b

array([[1, 2],
       [3, 4]])

In [61]:
np.hstack([a,b])

array([[1, 2, 3, 1, 2],
       [4, 5, 6, 3, 4]])

In [62]:
np.hstack([a,b,b])

array([[1, 2, 3, 1, 2, 1, 2],
       [4, 5, 6, 3, 4, 3, 4]])

### <span style='background :yellow'>Copiare array

#### Copia sbagliata

In [63]:
a = np.array([1,2,3], dtype='int8')
a

array([1, 2, 3], dtype=int8)

In [64]:
b = a # b copia a, ma una modifica di b comporta la modifica anche di a
b[0] = 100

In [65]:
a

array([100,   2,   3], dtype=int8)

In [66]:
b

array([100,   2,   3], dtype=int8)

#### Copia corretta

In [67]:
a = np.array([1,2,3], dtype='int8')
a

array([1, 2, 3], dtype=int8)

In [68]:
b = a.copy()
b[0] = 100

In [69]:
a

array([1, 2, 3], dtype=int8)

In [70]:
b

array([100,   2,   3], dtype=int8)

### <span style='background :yellow'>Array slicing

#### Array

In [71]:
# Creazione del vettore a
a = np.arange(0, 20, 2)
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

##### Modifica di un elemento

In [72]:
a[0] = 100 # modifica del primo elemento dell'array
a

array([100,   2,   4,   6,   8,  10,  12,  14,  16,  18])

##### Ottenere uno specifico elemento

In [73]:
a[2] # elemento in posizione 2

4

##### Ottenere un intervallo

In [74]:
b = a[1:6] # intervallo tra elementi in posizione 1 e (6-1)
b

array([ 2,  4,  6,  8, 10])

In [75]:
b = a[1:6:2] # intervallo tra elementi in posizione 1 e (6-1) con step di 2 elementi
b

array([ 2,  6, 10])

##### Ottenere i primi n elementi

In [76]:
b = a[:5] # primi 5 elementi
b

array([100,   2,   4,   6,   8])

##### Ottenere elementi da n in poi

In [77]:
b = a[5:] # da elemento 5 in poi
b

array([10, 12, 14, 16, 18])

##### Ottenere alcuni elementi

In [78]:
b = a[[1,2,8]] # elementi in posizione 1,2 e 8
b

array([ 2,  4, 16])

#### Matrici

In [79]:
# Creazione del vettore a
a = np.array([[0,1,2,3,4],[5,6,7,8,9]])
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

##### Modifica di un elemento

In [80]:
a[0,0] = 100
a

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9]])

##### Modifica di una riga

In [81]:
a[0,:] = 90 # singolo valore per tutta la riga
a

array([[90, 90, 90, 90, 90],
       [ 5,  6,  7,  8,  9]])

In [82]:
a[0,:] = [0,1,2,3,4] # lista di valori [] per modificare tutta la riga
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

##### Modifica di una colonna

In [83]:
a[:,2] = 90 # singolo valore per tutta la colonna
a

array([[ 0,  1, 90,  3,  4],
       [ 5,  6, 90,  8,  9]])

In [84]:
a[:,2] = [2,7] # lista di valori [] per modificare tutta la colonna
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

##### Modifica di un pezzo di matrice

In [85]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [86]:
a[0:2,1:3] = 90 # singolo valore per tutto il pezzo
a

array([[ 0, 90, 90,  3,  4],
       [ 5, 90, 90,  8,  9]])

In [87]:
a[0:2,1:3] = [[1,2],[6,7]] # matrice di valori [[],[]] per modificare il pezzo di matrice
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

##### Ottenere uno specifico elemento

In [88]:
a[1,2] # elemento a riga 1 colonna 2

7

In [89]:
b = a[0:1,1] # 0:1 prende solamente la posizione 0, perchè sarebbe da 0 ad (1-1) = 0, ma permette di mantere la struttura array (altrimenti restituirebbe un numero)
b

array([1])

##### Ottenere una specifica riga

In [90]:
b = a[1,:] # riga 1, tutte le colonne
b

array([5, 6, 7, 8, 9])

In [91]:
b = a[1] # riga 1, tutte le colonne (altro metodo)
b

array([5, 6, 7, 8, 9])

##### Ottenere una specifica colonna

In [92]:
b = a[:,1] # colonna 1, tutte le righe
b

array([1, 6])

In [93]:
b = a[...,1] # colonna 1, tutte le righe (altro metodo)
b

array([1, 6])

##### Ottenere un pezzo di matrice
Si possono applicare 4 metodi differenti

In [94]:
b = a[0:2,0:2] # sia righe che colonne tramite intervallo 
b

array([[0, 1],
       [5, 6]])

In [95]:
b = a[0:2,[0,1]] # righe tramite intervallo e colonne tramite lista
b

array([[0, 1],
       [5, 6]])

In [96]:
b = a[[0,1],0:2] # colonne tramite intervallo e righe tramite lista
b

array([[0, 1],
       [5, 6]])

In [97]:
b = a[[0,0,1,1],[0,1,0,1]] # righe e colonne tramite liste (in questo caso si ottiene un vettore monodimensionale)
b

array([0, 1, 5, 6])

### <span style='background :yellow'>Maschere booleane

In [98]:
# Creazione del vettore a
a = np.array([[0,1,200,4,5],[1,2,1,1,2]])

In [99]:
a

array([[  0,   1, 200,   4,   5],
       [  1,   2,   1,   1,   2]])

#### Creazione del filtro

In [100]:
mask_1 = ((a > 3) & (a < 200)) # filtro per valori della matrice 3 < a < 200
mask_1

array([[False, False, False,  True,  True],
       [False, False, False, False, False]])

In [101]:
mask_2 = ~mask_1 # filtro inverso
mask_2

array([[ True,  True,  True, False, False],
       [ True,  True,  True,  True,  True]])

#### Applicazione del filtro su tutta la matrice

In [102]:
c = a[mask_1]
c

array([4, 5])

#### Funzione ANY
La maschera viene applicata su tutte le righe o colonne (in base al parametro axis)
Basta che almeno un valore della riga o colonna rispetti la condizione per ritornare True

In [103]:
np.any(mask_1, axis=0) # applicazione della maschera sulle colonne

array([False, False, False,  True,  True])

In [104]:
np.any(mask_1, axis=1) # applicazione della maschera sulle righe

array([ True, False])

#### Funzione ALL
La maschera viene applicata su tutte le righe o colonne (in base al parametro axis)
Tutti i valori della riga o colonna devono rispettare la condizione per ritornare True

In [105]:
np.all(mask_1, axis=0) # applicazione della maschera sulle colonne

array([False, False, False, False, False])

In [106]:
np.all(mask_1, axis=1) # applicazione della maschera sulle righe

array([False, False])

### <span style='background :yellow'>Funzioni matematiche

In [107]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[-0.5,2.3,1],[-2.1,4.9,1]])

#### Funzione ADD - somma tra due array/matrici

In [108]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [109]:
b

array([[-0.5,  2.3,  1. ],
       [-2.1,  4.9,  1. ]])

In [110]:
c = np.add(a,b) # somma delle due matrici sopra
c

array([[0.5, 4.3, 4. ],
       [1.9, 9.9, 7. ]])

In [111]:
c = a + b # metodo alternativo
c

array([[0.5, 4.3, 4. ],
       [1.9, 9.9, 7. ]])

#### Funzione SUM - somma su assi di un array/matrice

In [112]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [113]:
c = a.sum(axis=0) # somma delle colonne
c

array([5, 7, 9])

In [114]:
c = a.sum(axis=1) # somma delle righe
c

array([ 6, 15])

#### Funzione CUMSUM - somma di tutti i valori di un array/matrice

In [115]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [116]:
c = np.cumsum(a, axis=0) # somma cumulativa su ogni colonna
c

array([[1, 2, 3],
       [5, 7, 9]])

In [117]:
c = np.cumsum(a, axis=1) # somma cumulativa su ogni riga
c

array([[ 1,  3,  6],
       [ 4,  9, 15]])

#### Funzione SUBTRACT - sottrazione tra due array/matrici

In [118]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [119]:
b

array([[-0.5,  2.3,  1. ],
       [-2.1,  4.9,  1. ]])

In [120]:
c = np.subtract(b,a) # somma delle due matrici sopra
c

array([[-1.5,  0.3, -2. ],
       [-6.1, -0.1, -5. ]])

In [121]:
c = b - a # metodo alternativo
c

array([[-1.5,  0.3, -2. ],
       [-6.1, -0.1, -5. ]])

#### Funzione MULTIPLY - prodotto tra due array/matrici

In [122]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [123]:
b

array([[-0.5,  2.3,  1. ],
       [-2.1,  4.9,  1. ]])

In [124]:
c = np.multiply(a,b) # prodotto delle due matrici sopra
c

array([[-0.5,  4.6,  3. ],
       [-8.4, 24.5,  6. ]])

In [125]:
c = a * b # metodo alternativo
c

array([[-0.5,  4.6,  3. ],
       [-8.4, 24.5,  6. ]])

#### Funzione DIVIDE - divisione tra due array/matrici

In [126]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [127]:
b

array([[-0.5,  2.3,  1. ],
       [-2.1,  4.9,  1. ]])

In [128]:
c = np.divide(b,a) # divisione delle due matrici sopra
c

array([[-0.5       ,  1.15      ,  0.33333333],
       [-0.525     ,  0.98      ,  0.16666667]])

In [129]:
c = b / a # metodo alternativo
c

array([[-0.5       ,  1.15      ,  0.33333333],
       [-0.525     ,  0.98      ,  0.16666667]])

#### Funzione REMAINDER - modulo divisione tra due array/matrici

In [130]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [131]:
b

array([[-0.5,  2.3,  1. ],
       [-2.1,  4.9,  1. ]])

In [132]:
c = np.remainder(b,a) # modulo divisione delle due matrici sopra
c

array([[0.5, 0.3, 1. ],
       [1.9, 4.9, 1. ]])

#### Funzione POWER - elevare a potenza un array/matrice

In [133]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [134]:
c = np.power(a,2) # potenza base 2 della matrice a
c

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

In [135]:
c = a ** 2 # metodo alternativo
c

array([[ 1,  4,  9],
       [16, 25, 36]])

#### Funzione EXP - esponenziale di un array/matrice

In [136]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [137]:
c = np.exp(a) # esponenziale della matrice a
c

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

#### Funzione SQRT - radice quadrata di un array/matrice

In [138]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [139]:
c = np.sqrt(a) # radice quadrata della matrice a
c

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

#### Funzione LOG - logaritmo naturale di un array/matrice

In [140]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [141]:
c = np.log(a) # logaritmo naturale della matrice a
c

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

#### Funzione AROUND - arrotondamento per eccesso o difetto di un array/matrice

In [142]:
b

array([[-0.5,  2.3,  1. ],
       [-2.1,  4.9,  1. ]])

In [143]:
c = np.around(b) # arrotondamento della matrice b
c

array([[-0.,  2.,  1.],
       [-2.,  5.,  1.]])

#### Funzione FLOOR - arrotondamento per difetto di un array/matrice

In [144]:
b

array([[-0.5,  2.3,  1. ],
       [-2.1,  4.9,  1. ]])

In [145]:
c = np.floor(b) # arrotondamento per difetto della matrice b
c

array([[-1.,  2.,  1.],
       [-3.,  4.,  1.]])

#### Funzione CEIL - arrotondamento per eccesso di un array/matrice

In [146]:
b

array([[-0.5,  2.3,  1. ],
       [-2.1,  4.9,  1. ]])

In [147]:
c = np.ceil(b) # arrotondamento per difetto della matrice b
c

array([[-0.,  3.,  1.],
       [-2.,  5.,  1.]])

#### Funzione TRUNC - eliminazione della parte decimale di un array/matrice

In [148]:
b

array([[-0.5,  2.3,  1. ],
       [-2.1,  4.9,  1. ]])

In [149]:
c = np.trunc(b) # arrotondamento per difetto della matrice b
c

array([[-0.,  2.,  1.],
       [-2.,  4.,  1.]])

#### Ulteriori funzioni

https://numpy.org/doc/stable/reference/routines.math

### <span style='background :yellow'>Algebra lineare

In [150]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2],[3,4],[5,6]])

#### Funzione MATMUL - prodotto matriciale tra due matrici

In [151]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [152]:
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [153]:
c = np.matmul(a,b)
c

array([[22, 28],
       [49, 64]])

#### Funzione LINALG.DET - determinante di una matrice

In [154]:
a = np.array([[1,0],[4,2]])
a

array([[1, 0],
       [4, 2]])

In [155]:
c = np.linalg.det(a)
c

2.0

#### Ulteriori funzioni

https://numpy.org/doc/stable/reference/routines.linalg

### <span style='background :yellow'>Funzioni statistiche

In [156]:
a = np.array([[1,7,3,9,5],[6,2,8,4,10]])

#### Funzione MIN - valore più piccolo di un array/matrice

In [157]:
a

array([[ 1,  7,  3,  9,  5],
       [ 6,  2,  8,  4, 10]])

In [158]:
c = np.min(a)
c

1

In [159]:
c = np.min(a, axis=0) # valore minimo su ogni colonna
c

array([1, 2, 3, 4, 5])

In [160]:
c = np.min(a, axis=1) # valore minimo su ogni riga
c

array([1, 2])

#### Funzione MAX - valore più grande di un array/matrice

In [161]:
a

array([[ 1,  7,  3,  9,  5],
       [ 6,  2,  8,  4, 10]])

In [162]:
c = np.max(a)
c

10

In [163]:
c = a.max(axis=0) # valore massimo su ogni colonna
c

array([ 6,  7,  8,  9, 10])

In [164]:
c = a.max(axis=1) # valore massimo su ogni riga
c

array([ 9, 10])

#### Funzione CORCOEFF - coefficente di correlazione di un array/matrice

In [165]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [166]:
c = np.corrcoef(a)
c

1.0

#### Funzione STD - deviazione standard
Probabilità che un valore si discosti dal valore medio

In [167]:
a = np.array([1,2,3,4,5])

In [168]:
a.mean() # la media è pari a 3

3.0

In [169]:
c = a.std()
c

1.4142135623730951

La deviazione standard è pari a 1.4. Ciò significa che un prossimo campione, con molta probabilità, si discosterà dalla media di +- 1.4
Più i campioni si avvicinano alla media, e più la deviazione standard diminuisce
Se tutti i campioni avessero lo stesso valore, la deviazione standard sarebbe pari a 0

In [170]:
a = np.array([3,3,3,3,3])

a.mean() # la media è pari a 3

c = a.std()
c

0.0

### <span style='background :yellow'>Lettura file

In [171]:
filedata = np.genfromtxt('random_numbers.txt', delimiter=',', dtype='int8')
filedata

array([[ 1,  4,  6,  7,  3,  4,  5],
       [ 3,  4,  2,  4,  5,  6, 21],
       [34,  6, 12, 45,  1, 34,  1]], dtype=int8)

### <span style='background :yellow'>Esercizio 1
Ricreare la seguente matrice

In [172]:
a = np.array([[0,0,0,0,0],[0,1,1,1,0],[0,1,9,1,0],[0,1,1,1,0],[0,0,0,0,0]])
a

array([[0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 9, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 0, 0, 0, 0]])

#### Soluzione 1

In [173]:
a = np.zeros((5,5), dtype = 'int32') # creo matrice 5x5 di tutti 0
a

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [174]:
b = np.ones((3,3), dtype = 'int32') # creo matrice 3x3 di tutti 1
b

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [175]:
b[1,1] = 9 # inserisco 9 nel centro della matrice più piccola
b

array([[1, 1, 1],
       [1, 9, 1],
       [1, 1, 1]])

In [176]:
a[1:4,1:4] = b # sostituisco centro della matrice a con la matrice b
a

array([[0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 9, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 0, 0, 0, 0]])

#### Soluzione 2

In [177]:
a = np.zeros((5,5), dtype = 'int32') # creo matrice 5x5 di tutti 0
a

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [178]:
a[1:4,1:4] = np.ones((3,3))
a

array([[0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 0, 0, 0, 0]])

In [179]:
a[2,2] = 9
a

array([[0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 9, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 0, 0, 0, 0]])

### <span style='background :yellow'>Esercizio 2

In [180]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

#### Estrarre il quadrato (11,12,16,17)

In [181]:
a[2:4,0:2]

array([[11, 12],
       [16, 17]])

In [182]:
a[2:4,[0,1]] # altro metodo

array([[11, 12],
       [16, 17]])

#### Estrarre la diagonale (2,8,14,20)

In [183]:
a[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

#### Estrarre i due pezzi (4,5) e (24,25,29,30)

In [184]:
a[[0,4,5],3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])